### ISSUE TITLE
Upgrade diesel to 2.0

### ISSUE THREAD

**Issue by dennismarwood** [dennismarwood/Rocket_back#6]
Check to see if diesel 2.0 will work with rocket.
https://github.com/SergioBenitez/Rocket/pull/2242

**Comment by Asone** [comment]
F.I : until the mentioned commit gets integrated to a next release of Rocket, diesel 2.0.0 won't be able to run with rocket ( moreover if your intend to use rocket_db_sync_pool ) [unless you use a specific rev](https://stackoverflow.com/a/54197014/7226358) in your cargo.toml file.

**Comment by dennismarwood** [comment]
https://github.com/dennismarwood/Rocket_back/commit/06a1dafce0dfc4d842f3bac094531eaa020c4057 and https://github.com/dennismarwood/Rocket_back/commit/126f48a769aa31f346cc29c967b9d6e0388f0b2b and https://github.com/dennismarwood/Rocket_back/commit/6a2f9d1f17755275e007b3e71315a74abf8c255e and https://github.com/dennismarwood/Rocket_back/commit/c588c4ccb8616b12d26b79b9676d9305d98d32a0
